### ISSUE TITLE
Installation error: invalid class "RdaCollection" object

### ISSUE THREAD

**Issue by AlexandreLaverre** [biomystery/BSgenome.Mmusculus.UCSC.mm10.masked#1]
Hello, 

Thank you for adding a TRF mask to the mm10 genome but I can't install it...
I got an "Error: loading failed" during the installation process (see below).

Do you have any idea how to fix it?
Thanks!

Alexandre

** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for 'BSgenome.Mmusculus.UCSC.mm10.masked':
 .onLoad failed in loadNamespace() for 'BSgenome.Mmusculus.UCSC.mm10.masked', details:
  call: validObject(.Object)
  error: invalid class "RdaCollection" object: 
    files
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr1_GL455991_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr1_GL455992_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr1_GL455993_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr1_GL456005_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr1_JH584315_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr1_JH584320_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr1_JH584321_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr1_JH584322_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr2_GL456024_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_GL456006_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_GL456007_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_GL456008_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_GL456042_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_GL456044_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_GL456045_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_GL456048_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_GL456049_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr3_JH584323_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_GL455994_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_GL456009_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_GL456010_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_GL456053_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_GL456064_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_GL456075_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_GL456076_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_GL456077_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_JH584268_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_JH584269_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_JH584324_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_JH584325_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr4_JH584326_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr5_GL455995_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr5_GL456011_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr6_GL456012_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr6_GL456025_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr6_GL456026_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr6_GL456054_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr6_GL456065_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr6_JH584264_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr7_GL455989_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr7_GL456013_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenome.Mmusculus.UCSC.mm10.masked/extdata/chr7_GL456014_alt.masks.rda',
    '/users/alaverre/Tools/mambaforge/envs/TestPos/lib/R/library/00LOCK-BSgenome.Mmusculus.UCSC.mm10.masked/00new/BSgenom
Error: loading failed
Execution halted
ERROR: loading failed

**Comment by EZUY** [comment]
Same question here

**Comment by biomystery** [comment]
Try this one instead: http://bioconductor.org/packages/release/data/annotation/html/BSgenome.Mmusculus.UCSC.mm10.masked.html 

I am not maintain this anymore.
